#ifndef EPOCHSYNC_VERSION_H
#define EPOCHSYNC_VERSION_H

#define EPOCHSYNC_NAME           "EpochSync"

#define EPOCHSYNC_VERSION_MAJOR  0
#define EPOCHSYNC_VERSION_MINOR  1
#define EPOCHSYNC_VERSION_PATCH  0

#endif