#ifndef EPOCHSYNC_TYPES_H
#define EPOCHSYNC_TYPES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <tamtypes.h>

typedef enum
{
	/* Success */
	EPOCHSYNC_SUCCESS = 0,

	/* Generic */
	EPOCHSYNC_ERROR_UNKNOWN,
	EPOCHSYNC_ERROR_INVALID_ARGUMENT,
	EPOCHSYNC_ERROR_NOT_IMPLEMENTED,

	/* Configuration */
	EPOCHSYNC_ERROR_CONFIG,

	/* File System */
	EPOCHSYNC_ERROR_FILE,
	EPOCHSYNC_ERROR_FILE_NOT_FOUND,
	EPOCHSYNC_ERROR_FILE_READ,
	EPOCHSYNC_ERROR_FILE_WRITE,

	/* Network */
	EPOCHSYNC_ERROR_NETWORK,
	EPOCHSYNC_ERROR_NETWORK_TIMEOUT,
	EPOCHSYNC_ERROR_DNS,
	EPOCHSYNC_ERROR_NTP,

	/* RTC */
	EPOCHSYNC_ERROR_RTC,
	EPOCHSYNC_ERROR_RTC_READ,
	EPOCHSYNC_ERROR_RTC_WRITE,

	/* Launcher */
	EPOCHSYNC_ERROR_LAUNCHER,

	/* UI */
	EPOCHSYNC_ERROR_UI

} EpochSyncResult;

typedef enum
{
	APPLICATION_STATE_INITIALIZE,
	APPLICATION_STATE_LOAD_CONFIG,
	APPLICATION_STATE_INITIALIZE_NETWORK,
	APPLICATION_STATE_SYNC_TIME,
	APPLICATION_STATE_CONFIRM,
	APPLICATION_STATE_WRITE_RTC,
	APPLICATION_STATE_LAUNCH,
	APPLICATION_STATE_EXIT

} ApplicationState;

typedef enum
{
	LOG_LEVEL_DEBUG,
	LOG_LEVEL_INFO,
	LOG_LEVEL_WARNING,
	LOG_LEVEL_ERROR
} LogLevel;

typedef enum
{
	NETWORK_STATE_OFFLINE,
	NETWORK_STATE_INITIALIZING,
	NETWORK_STATE_CONNECTING,
	NETWORK_STATE_CONNECTED
} NetworkState;

#endif // EPOCHSYNC_TYPES_H

