#ifndef EPOCHSYNC_VERSION_H
#define EPOCHSYNC_VERSION_H

#define EPOCHSYNC_NAME      "EpochSync"

#define EPOCHSYNC_VERSION_MAJOR  0
#define EPOCHSYNC_VERSION_MINOR  2
#define EPOCHSYNC_VERSION_PATCH  1

#define EPOCHSYNC_VERSION_STRING "0.2.1"

#define EPOCHSYNC_AUTHOR    "BLACKSTAR"
#define EPOCHSYNC_COPYRIGHT "(C) 2026 BLACKSTAR"

#endif /* EPOCHSYNC_VERSION_H */