#ifndef EPOCHSYNC_VERSION_H
#define EPOCHSYNC_VERSION_H

#define EPOCHSYNC_NAME      "EpochSync"

#define EPOCHSYNC_VERSION_MAJOR  0
#define EPOCHSYNC_VERSION_MINOR  1
#define EPOCHSYNC_VERSION_PATCH  0

#define EPOCHSYNC_VERSION_STRING "0.1.0"

#define EPOCHSYNC_AUTHOR    "BLACKSTAR"
#define EPOCHSYNC_COPYRIGHT "(C) 2026 BLACKSTAR"

#endif